N2 - Projeto de Aplicacao Imagem/joaquim felix/N2/N2/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from image import views

from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', views.photo_list, name='photo_list'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

N2 - Projeto de Aplicacao Imagem/joaquim felix/N2/image/models.py
from django.db import models

class Photo(models.Model):
    file = models.ImageField(upload_to='media',null = True, blank = True)
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

    def __str__(self):
        return str(self.pk)

N2 - Projeto de Aplicacao Imagem/joaquim felix/N2/image/forms.py
from PIL import Image
from django import forms
from django.core.files import File
from .models import Photo

class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

N2 - Projeto de Aplicacao Imagem/joaquim felix/N2/image/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from PIL import Image
from .models import Photo
from .forms import PhotoForm


def photo_list(request):
    photos = Photo.objects.all()
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('photo_list')

    else:
        form = PhotoForm()
    context = {'form': form, 'photos': photos}
    return render(request, 'main.html', context)

N2 - Projeto de Aplicacao Imagem/joaquim felix/N2/templates/main.html
{%extends "model-page.html"%}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{%block content%}
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column bg-dark">
  <header class="mb-auto">
    <div>
      <h3 class="mb-auto">JF</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="#"></a>
      </nav>
    </div>
  </header>
</div>

<main class="px-3 " >
  <div class="modal-content rounded-5 shadow" style="size:720px;">
    <div class="mb-3">
      <div  style="margin-top: 20px">
        <div >
          
          <img src="{{photo.file.url}}" class="img-fluid" />
          
        </div>
      </div>
    </div> 
         
        {%include "nav.html"%}
        
        <h1 style="color:#000;">Coloque uma imagem</h1>
          <a class="btn btn-lg btn-primary mt-3 fw-bold border-white bg-dark " >
       <form method="post" enctype="multipart/form-data" id="formUpload">
          {% csrf_token %}
          {{ form }}
       </form>
    </a>
  </div>
</main>

<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

N2 - Projeto de Aplicacao Imagem/joaquim felix/N2/templates/model-footer.html
<footer class="navbar-fixed-bottom" >
    <p class="col-md-4 mb-0 text-muted">© 2021 Joaquim Felix(JFKING)
        <i class="fas fa-crown"></i>
    </p>
    
  </footer>

N2 - Projeto de Aplicacao Imagem/joaquim felix/N2/templates/model-header.html
{% load static %}
<head>
  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href={% static 'style.css' %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.css">
    
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js"></script>
    <script src={% static 'main.js' %} defer></script>
    
    <title>Atividade N2</title>
    
</head>

N2 - Projeto de Aplicacao Imagem/joaquim felix/N2/templates/model-page.html
<!DOCTYPE html>
<html>
<head>
	{%include "model-header.html"%}

</head>
<body class=" h-100 text-center text-white " >
      
<div class="container">
      {% block content %}
      {% endblock %}
</div>
{% block javascript %}
{% endblock %}
</body>
{%include "model-footer.html"%}
</html>

N2 - Projeto de Aplicacao Imagem/joaquim felix/N2/templates/nav.html
<div class="d-flex flex-column flex-shrink-0 bg-light" style="width: 4.5rem;">
    <a href="image/" class="d-block p-3 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only">
      <i class="fas fa-crop-alt"><use ></use></i>
      <span class="visually-hidden">Icon-only</span>
    </a>
    <ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
      <li class="nav-item">
        <a href="/" class="nav-link active py-3 border-bottom" aria-current="page" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
          <i class="fas fa-home"><use xlink:href="{% url 'photo_list' %}"></i>
        </a>
      </li>
      <li>
        <a href="#" class="nav-link py-3 border-bottom" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Dashboard">
          <svg class="bi" width="24" height="24" role="img" aria-label="Dashboard"><use xlink:href="#speedometer2"></use></svg>
        </a>
      </li>
      <li>
        <a href="#" class="nav-link py-3 border-bottom" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Orders">
          <svg class="bi" width="24" height="24" role="img" aria-label="Orders"><use xlink:href="#table"></use></svg>
        </a>
      </li>
      <li>
        <a href="#" class="nav-link py-3 border-bottom" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Products">
          <svg class="bi" width="24" height="24" role="img" aria-label="Products"><use xlink:href="#grid"></use></svg>
        </a>
      </li>
      <li>
        <a href="#" class="nav-link py-3 border-bottom" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Customers">
          <svg class="bi" width="24" height="24" role="img" aria-label="Customers"><use xlink:href="#people-circle"></use></svg>
        </a>
      </li>
    </ul>
    <li>
        <a href="#" class="nav-link py-3 border-bottom" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Customers">
          <svg class="bi" width="24" height="24" role="img" aria-label="Customers"><use xlink:href="#people-circle"></use></svg>
        </a>
      </li>
    </ul>
  </div>